### ISSUE TITLE
Shadowlands: WorldQuests.lua line 276:    attempt to call method '?' (a nil value) (BWQ:SetBackdrop)

### ISSUE THREAD

**Issue by yoshimo** [xmyno/Broker_WorldQuests#46]
Maybe https://github.com/Nevcairiel/ShadowedUnitFrames/commit/9157cb5561168a47afe4b967b00905c166b04c6d can help

**Comment by yoshimo** [comment]
Unlock of the Shadowland WQs should be 57559  at level 60

**Comment by xmyno** [comment]
Sorry for the silence. Thank you for the effort of reporting these changes. Unfortunately I have not been following the game and have no intention of returning to WoW, so I won't be working on any further updates. Again, sorry.

If someone is interested in continuing the project feel free to contact me. Otherwise there are probably better alternatives available.

**Comment by yoshimo** [comment]
I can add new factions and zones, but this time i need someone else to attempt fixes on which i can continue. Blizzard likes to make annoying changes.

**Comment by yoshimo** [comment]
Backdrop errors are fixed; still messing around with GetQuestTagInfo and related things to show quests again in #47
