### ISSUE TITLE
release 11.0.2.9 missing assets

### ISSUE THREAD

**Issue by torkus** [xmyno/Broker_WorldQuests#65]
Hi there, I noticed the most recent release, [11.0.2.9](https://github.com/xmyno/Broker_WorldQuests/releases/tag/11.0.2.9) is missing the usual addon .zip file and the release.json file.

It looks like the build failed with some permissions problem: https://github.com/xmyno/Broker_WorldQuests/actions/runs/10651724661/job/29524636984

**Comment by Amadeus-** [comment]
I'm not sure what you mean ... when I go to https://github.com/xmyno/Broker_WorldQuests/releases/tag/11.0.2.9 , I see the assets at the bottom of the page.

The build failures have to do with this repository's configuration.  I'm only a collaborator (so I don't have permissions to change the settings) and the original author hasn't been around in years so it's likely going to stay broken.   But -- folks can just ignore those errors....I'll manually create releases occasionally, just like I did last week.

All that being said, your best bet is to use my fork directly, as it will always have the latest updates and it's also the repository being used by the Curseforge release page.  It's at https://github.com/Amadeus-/Broker_WorldQuests

**Comment by torkus** [comment]
> I'm not sure what you mean ... when I go to https://github.com/xmyno/Broker_WorldQuests/releases/tag/11.0.2.9 , I see the assets at the bottom of the page.

Here is what I see for 11.0.2.9:
![Screenshot at 2024-09-10 20-55-09](https://github.com/user-attachments/assets/a8184afb-eb8a-4a5e-bd1b-af85da16d841)

And for ~11.0.2.1~ 10.0.2.1 (the previous release):
![Screenshot at 2024-09-10 20-54-54](https://github.com/user-attachments/assets/dd17ad0b-8ad4-4ad5-b883-0982fe1bddc2)

> All that being said, your best bet is to use my fork directly, ...

I maintain a [catalogue of Github hosted wow addons](https://github.com/ogri-la/github-wow-addon-catalogue-go) and noticed this one disappear because of the missing release assets.

**Comment by Amadeus-** [comment]
Oh -- well, Source Code (zip) has everything in that Broker_WorldQuests-10.0.2.1.zip would have had in it.  

The official release of this addon is on Curse and it now uses my fork, not this repo.   Curse creates the named .zip file itself whenever I create a release manually.

Anyway, long story short is that any catalogue including this addon should use the Curseforge page rather than the github repository, because the github repository may (will likely) change any time the maintainer of the addon changes.
