### ISSUE TITLE
RFE: Sum of rewards in tooltip

### ISSUE THREAD

**Issue by mortenn** [xmyno/Broker_WorldQuests#8]
Would be neat to see at a glance how much power, rep, and gold could be grabbed by doing all the currently filtered WQs in the popup, but certainly not a high priority enhancement :)

**Comment by xmyno** [comment]
Amount of artifact power is already in if you have text enabled for the broker element. I might improve the "header" of the list to include things like this as well instead of just the bounty display.

Gold and resources would not be a problem, rep on the other side is not possible other than defining the reputation rewarded for each quest manually, which I'm not really keen on doing, or giving an approximate value (75 for normal, 250 for rare quest).

**Comment by mortenn** [comment]
I do have text enabled, but I don't see a grand total of the artefact power, only per quest.

**Comment by xmyno** [comment]
May I ask what broker display addon you are using?

**Comment by mortenn** [comment]
I am using titan panel

**Comment by xmyno** [comment]
Sorry for the late reply. Just had a look at Titan Panel and it's working fine for me.
Make sure you have 'Show Plugin Text' enabled for the broker plugin, see:

![example](http://i.imgur.com/hklr4y0.png)

**Comment by mortenn** [comment]
That's ok, I'm in no hurry ^_^
I think you may have misunderstood what I meant..
Each WQ in the list shows how much they award, what I am asking for is a 
summary of all the WQs at the bottom.

Cheers, Morten

**Comment by xmyno** [comment]
Top left of the image is the broker text. Since r24 it can show the sum of AP, Resources, Gold, Blood of Sargeras, Gear, Fishing, Mining and Herbalism Quests currently available (including options to turn them on/off individually). Thought that's what you meant, isn't it?

Edit: Ah, you want that in the tooltip too, it's even in the title, duh. I'll see if I can fit it somewhere.

**Comment by mortenn** [comment]
Oh, in the titan panel bar itself?
That is not what I was looking for, I only wanted it in the tooltip that 
appears when I hover the icon.

   -- Morten
